# Usage: .\scripts\set-xai-key.ps1 -Key "xai-..."
# Writes XAI_API_KEY into project .env (never commit .env)
param(
  [Parameter(Mandatory = $true)]
  [string]$Key
)

$root = Split-Path -Parent (Split-Path -Parent $MyInvocation.MyCommand.Path)
$envFile = Join-Path $root ".env"
$Key = $Key.Trim()
if (-not $Key) { throw "Key is empty" }

@"
# SpaceXAI (xAI) — https://console.x.ai
# Generated by scripts/set-xai-key.ps1 — do not commit
XAI_API_KEY=$Key
"@ | Set-Content -Path $envFile -Encoding UTF8

Write-Host "Wrote XAI_API_KEY to $envFile"
Write-Host "Restart Rehearse: npm run electron:dev"
